### ISSUE TITLE
invalid credential error

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusClient#4]
I installed a fresh copy of R latest build (3.4.2) on Windows

Ran the following code:

install.packages("devtools")
library(devtools)
install_github("jbrzusto/motusClient")
library(motusClient)
tagme(16,new=TRUE)

src:  sqlite 3.19.3 [C:\Users\dlepage\Documents\project-16.motus]
tbls: alltags, antDeps, batches, batchRuns, gps, hits, meta, projAmbig,
  projBatch, projs, recvDeps, recvs, runs, species, tagAmbig, tagDeps, tags

tagme(16,update=TRUE)

<enter credentials>

<wait for a long while>

Auto-disconnecting SQLiteConnection
Error in value[[3L]](cond) : 
  The motus data server rejected your login credentials

I tried several times, update all packages, reinstalled R, tried from the earlier version 3.4.1, tried with severl logins, etc. I am always getting the same result.

**Comment by jbrzusto** [comment]
actually a server error
closing in deference to jbrzusto/motusServer#276

**Comment by jbrzusto** [comment]
the same function was broken in this package, although I'm not sure it's used.
So it's safest to update your copy of motusClient.

**Comment by denislepage** [comment]
updated the client, but error persists.

**Comment by jbrzusto** [comment]
did you restart R after updating?  I'm not seeing this error with the new motusClient,
whereas I did with the old one.

**Comment by denislepage** [comment]
I don’t know that I did previously, but the latest attempt appears to be working.
