### ISSUE TITLE
response encoding

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusClient#9]
motusClient doesn't seem to be handling UTF-8 encoding properly.

E.g. with metadata_for_tag_project, projectID = 56, motusTagIDs = [19937]

the species table has the French name as "Paruline rayÃ©e". This is happening with both SG and Motus API's. They are returning the response as UTF-8, but the motusClient seems to assume they are ANSI at some point along the way.

This is presumably something happening in srvQuery, in one of the following lines.

        if (requestType == "post")
            resp = RCurl::postForm(URL, json=json, style="post", curl=curl, .contentEncodeFun=RCurl::curlPercentEncode)
        else
            resp = RCurl::getForm(URL, json=json, curl=curl)
        resp = memDecompress(structure(resp, `Content-Type`=NULL), "bzip2", asChar=TRUE)
        
        if (JSON)
            return (resp)
        if (grepl("^[ \r\n]*$", resp))
            return(list())
        rv = jsonlite::fromJSON(resp)

If I do this when loading metadata for project 56, I get UTF-8

    x = srvQuery(API=Motus$API_METADATA_FOR_TAGS, params=list(motusTagIDs=motusTagIDs))
    cat(x$species[[3]])
    cat(Encoding(x$species[[3]]))

Grive Ã  dos olive Paruline Ã  tÃªte cendrÃ©e Paruline rayÃ©e
UTF-8 UTF-8 UTF-8

**Comment by jbrzusto** [comment]
I'm not seeing this with the jbrzusto/motusClient package running under R 3.4.0 on linux:
```R
> library(motusClient)
...
> s=tagme(56, new=TRUE, update=TRUE)
Checking for new data in project 56
Project    56:  got   215 batch records
src:  sqlite 3.11.1 [/home/sg/test/project-56.motus]s starting at               0
tbls: alltags, antDeps, batches, batchRuns, clarified, gps, hits, meta,
  projAmbig, projBatch, projs, recvDeps, recvs, runs, species, tagAmbig,
  tagDeps, tags
> uu=tbl(s, "species") %>% as.data.frame
> dim(uu)
[1] 3 6
> uu
     id           english                  french         scientific group sort
1 15580 Swainson's Thrush       Grive à dos olive Catharus ustulatus BIRDS   NA
2 16580  Magnolia Warbler Paruline à tête cendrée Setophaga magnolia BIRDS   NA
3 16820 Blackpoll Warbler          Paruline rayée  Setophaga striata BIRDS   NA
> Encoding(uu$french)
[1] "UTF-8" "UTF-8" "UTF-8"
```
Perhaps it's an issue with R under Windows.  How are you accessing the `species` table and
seeing non-UTF-8-encoded names?

**Comment by denislepage** [comment]
Sounds like an OS issue;

When I run your code below, both against your server API and Motus, I get the same problem. Zoe is also seeing this on her Mac.

     id           english                     french         scientific group sort
1 15580 Swainson's Thrush         Grive Ã  dos olive Catharus ustulatus BIRDS   NA
2 16580  Magnolia Warbler Paruline Ã  tÃªte cendrÃ©e Setophaga magnolia BIRDS   NA
3 16820 Blackpoll Warbler            Paruline rayÃ©e  Setophaga striata BIRDS   NA


Encoding(uu$french)
[1] "UTF-8" "UTF-8" "UTF-8"

Let me know if you have any suggestions on how to fix this in the R code. The API’s are both providing UTF-8 encoding, which I can confirm in a Java client.

It almost has to be in one of those lines in srvQuery. I tried to add encoding=”utf-8” to getForm, but that didn’t change anything. My guess is it is more likely in the decompress stage, with the asChar=TRUE option.

    if (requestType == "post")
        resp = RCurl::postForm(URL, json=json, .encoding="utf-8", style="post", curl=curl, .contentEncodeFun=RCurl::curlPercentEncode)
    else
        resp = RCurl::getForm(URL, json=json, .encoding="utf-8", curl=curl)
    resp = memDecompress(structure(resp, `Content-Type`=NULL), "bzip2", asChar=TRUE)


This is giving me the same result:
intToUtf8(memDecompress(structure(resp, `Content-Type`=NULL), "bzip2", asChar=FALSE))


I’m stumped.

**Comment by denislepage** [comment]
iconv seems to fix it for me, when used as follow. Can you confirm that it also works in Linux?

resp = iconv(memDecompress(structure(resp, `Content-Type`=NULL), "bzip2", asChar=TRUE),"utf-8")

**Comment by jbrzusto** [comment]
What do you get if you do this in R:
```R
rawToChar(as.raw(c(0xc3, 0xa9)))
```
If you get 
```R
[1] "Ã©"
```
then R on your platform is using "latin1" encoding by default.
Then the `memDecompress()`, which calls `rawToChar()`, is treating
the decompressed bytes as representing characters under that encoding.

~~According to  [this](https://stackoverflow.com/questions/31308541/r-default-encoding-to-utf-8) you can apparently change that in your R session by doing:
`options(encoding="UTF-8")` or `options(encoding="UTF-8-BOM")`
but I'm unable to test this.~~  
Just tested, and In R-3.0 under Windows 7, setting this option does not cause strings
created by `rawToChar` to have UTF-8 encoding, so this is **not** a fix.

**Comment by jbrzusto** [comment]
```R
resp = iconv(memDecompress(structure(resp, Content-Type=NULL), "bzip2", asChar=TRUE),"UTF-8")
```
works but since my call to `structure()` isn't doing anything useful in recent R
```
resp = iconv(memDecompress(resp, "bzip2", asChar=TRUE),"UTF-8")
```
also works.

**Comment by jbrzusto** [comment]
But note that you're then left with a string in your platform's native encoding, rather than one
in UTF-8.  That's going to be a problem if there are characters unsupported in the native encoding.
So perhaps this makes more sense:
```R
resp = memDecompress(resp, "bzip2", asChar=TRUE)
Encoding(resp) = "UTF-8"
```
which should mark the string as encoded in UTF-8, regardless of platform default.  And
this avoids having to tell R to default to "UTF-8" in general.

If you can confirm the above works, I'll make the change to `motusClient::srvQuery()`

**Comment by jbrzusto** [comment]
The code in the previous comment works on R-3.0 under Windows 7.
It is a lighter-weight approach than using `iconv()`, because it's just adding a tag
to the string, rather than manipulating the underlying bytes.

So f2528f10a5cc1270ca4db9097fe0bf01d58b92bc closes this.

**Comment by denislepage** [comment]
thanks, seems to work well.

Denis
